# Generated by Django 3.2.7 on 2021-09-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20210926_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('created',), 'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('livestock', 'livestock'), ('poultry', 'poultry'), ('aquatic', 'aquatic')], max_length=11),
        ),
    ]
