# Generated by Django 3.2.7 on 2021-09-26 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20210926_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='insurance_from_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
