# Generated by Django 3.2.7 on 2021-09-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20210926_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='info.insurance'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='insurance_condition',
            field=models.CharField(choices=[('finished', 'finished'), ('valid', 'valid'), ('empty', 'empty')], max_length=10),
        ),
        migrations.AlterField(
            model_name='condition',
            name='insurance_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='condition',
            name='insurance_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
