# Generated by Django 3.2.7 on 2021-09-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20210929_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='age',
        ),
        migrations.AddField(
            model_name='info',
            name='birthـmonth',
            field=models.DateField(default='2021-09-15'),
        ),
    ]
