# Generated by Django 3.2.7 on 2021-09-29 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20210929_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='birthـmonth',
        ),
        migrations.AddField(
            model_name='info',
            name='dateـofـbirth',
            field=models.DateField(default=datetime.datetime(2021, 9, 29, 11, 56, 17, 918629)),
        ),
    ]
