# Generated by Django 3.2.7 on 2021-09-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
