# Generated by Django 3.2.7 on 2021-09-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0006_auto_20210929_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='infoImage/'),
        ),
    ]
