# Generated by Django 3.2.7 on 2021-09-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0007_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='infoFile/'),
        ),
    ]
