# Generated by Django 3.1.1 on 2020-09-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_rest_phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
