# Generated by Django 3.1.1 on 2020-09-30 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_rest_phone', '0003_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=150, null=True, unique=True, validators=[django.core.validators.EmailValidator(code='invalid_email')]),
        ),
    ]
