# Generated by Django 3.1.2 on 2020-10-04 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_rest_phone', '0004_auto_20200930_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09999999999'. Up to 11 digits allowed.", regex='^09[0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09999999999'. Up to 11 digits allowed.", regex='^09[0-9]{9}$')]),
        ),
    ]
