# Generated by Django 3.1.2 on 2020-10-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_rest_phone', '0005_auto_20201004_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='avatar'),
        ),
    ]
