# Generated by Django 3.1.2 on 2020-10-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_rest_phone', '0006_auto_20201017_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='avatar'),
        ),
    ]
