# Generated by Django 3.1.2 on 2020-10-19 10:24

import auth_rest_phone.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_rest_phone', '0009_phoneotp_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default_avatar.jpg', null=True, upload_to=auth_rest_phone.models.UserProfile.user_directory_path),
        ),
    ]
